# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64\x65tection.proto\"F\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"\x1f\n\x07Point2d\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"2\n\x04Rect\x12\x14\n\x02tl\x18\x01 \x01(\x0b\x32\x08.Point2d\x12\x14\n\x02\x62r\x18\x02 \x01(\x0b\x32\x08.Point2d\"T\n\tDetection\x12\x12\n\nconfidence\x18\x01 \x01(\x02\x12\x10\n\x08label_id\x18\x02 \x01(\r\x12\r\n\x05label\x18\x03 \x01(\t\x12\x12\n\x03\x62ox\x18\x04 \x01(\x0b\x32\x05.Rect\",\n\nDetections\x12\x1e\n\ndetections\x18\x01 \x03(\x0b\x32\n.Detection2<\n\x10\x44\x65tectionService\x12(\n\x0fObjectDetection\x12\x06.Image\x1a\x0b.Detections\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='Image.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='Image.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='Image.encoding', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Image.data', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=89,
)


_POINT2D = _descriptor.Descriptor(
  name='Point2d',
  full_name='Point2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point2d.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point2d.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=122,
)


_RECT = _descriptor.Descriptor(
  name='Rect',
  full_name='Rect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tl', full_name='Rect.tl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='br', full_name='Rect.br', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=174,
)


_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='Detection.confidence', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_id', full_name='Detection.label_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='Detection.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box', full_name='Detection.box', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=260,
)


_DETECTIONS = _descriptor.Descriptor(
  name='Detections',
  full_name='Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='Detections.detections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=306,
)

_RECT.fields_by_name['tl'].message_type = _POINT2D
_RECT.fields_by_name['br'].message_type = _POINT2D
_DETECTION.fields_by_name['box'].message_type = _RECT
_DETECTIONS.fields_by_name['detections'].message_type = _DETECTION
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Point2d'] = _POINT2D
DESCRIPTOR.message_types_by_name['Rect'] = _RECT
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'detection_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)

Point2d = _reflection.GeneratedProtocolMessageType('Point2d', (_message.Message,), dict(
  DESCRIPTOR = _POINT2D,
  __module__ = 'detection_pb2'
  # @@protoc_insertion_point(class_scope:Point2d)
  ))
_sym_db.RegisterMessage(Point2d)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), dict(
  DESCRIPTOR = _RECT,
  __module__ = 'detection_pb2'
  # @@protoc_insertion_point(class_scope:Rect)
  ))
_sym_db.RegisterMessage(Rect)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), dict(
  DESCRIPTOR = _DETECTION,
  __module__ = 'detection_pb2'
  # @@protoc_insertion_point(class_scope:Detection)
  ))
_sym_db.RegisterMessage(Detection)

Detections = _reflection.GeneratedProtocolMessageType('Detections', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONS,
  __module__ = 'detection_pb2'
  # @@protoc_insertion_point(class_scope:Detections)
  ))
_sym_db.RegisterMessage(Detections)



_DETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='DetectionService',
  full_name='DetectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=308,
  serialized_end=368,
  methods=[
  _descriptor.MethodDescriptor(
    name='ObjectDetection',
    full_name='DetectionService.ObjectDetection',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_DETECTIONS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTIONSERVICE)

DESCRIPTOR.services_by_name['DetectionService'] = _DETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
