// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection.proto

#include "detection.pb.h"
#include "detection.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* DetectionService_method_names[] = {
  "/DetectionService/ObjectDetection",
};

std::unique_ptr< DetectionService::Stub> DetectionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DetectionService::Stub> stub(new DetectionService::Stub(channel));
  return stub;
}

DetectionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ObjectDetection_(DetectionService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DetectionService::Stub::ObjectDetection(::grpc::ClientContext* context, const ::Image& request, ::Detections* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ObjectDetection_, context, request, response);
}

void DetectionService::Stub::experimental_async::ObjectDetection(::grpc::ClientContext* context, const ::Image* request, ::Detections* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ObjectDetection_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::Detections>* DetectionService::Stub::AsyncObjectDetectionRaw(::grpc::ClientContext* context, const ::Image& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Detections>::Create(channel_.get(), cq, rpcmethod_ObjectDetection_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Detections>* DetectionService::Stub::PrepareAsyncObjectDetectionRaw(::grpc::ClientContext* context, const ::Image& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Detections>::Create(channel_.get(), cq, rpcmethod_ObjectDetection_, context, request, false);
}

DetectionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DetectionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DetectionService::Service, ::Image, ::Detections>(
          std::mem_fn(&DetectionService::Service::ObjectDetection), this)));
}

DetectionService::Service::~Service() {
}

::grpc::Status DetectionService::Service::ObjectDetection(::grpc::ServerContext* context, const ::Image* request, ::Detections* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


